baseurl = "https://denseanalysis.org"
DefaultContentLanguage = "en"
title = "Dense Analysis"
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  homeTitle = "Dense Analysis"
  subtitle = "\"Dense Analysis trumps speculation\""
  mainSections = ["post","posts"]
  logo = "img/da-logo.png" # Expecting square dimensions
  favicon = "img/da-favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = false
  delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  # There are many built in options.
  # See: themes/beautifulhugo/data/beautifulhugo/social.toml

  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  website = "yourwebsite.com"
  # email = "youremail@domain.com"
  github = "dense-analysis"
  # youtube = "user/username"
  discord = "https://discord.gg/5zFD6pQxDk"

[[menu.main]]
    identifier = "products"
    name = "Products"
    weight = 1

[[menu.main]]
    parent = "products"
    name = "DAFT"
    url = "products/daft/"

[[menu.main]]
    identifier = "services"
    name = "Services"
    weight = 2

[[menu.main]]
    parent = "services"
    name = "Speaking"
    url = "services/speaking/"
    weight = 1

[[menu.main]]
    parent = "services"
    name = "Community"
    url = "services/community/"
    weight = 2

# [[menu.main]]
#     identifier = "resources"
#     name = "Resources"
#     weight = 3
#
# [[menu.main]]
#     parent = "resources"
#     identifier = "blog"
#     name = "Blog"

[[menu.main]]
    identifier = "about"
    name = "About"
    weight = 4


[[menu.main]]
    parent = "about"
    name = "Org"
    url = "about/organization/"
    weight = 1

[[menu.main]]
    parent = "about"
    name = "Why FOSS?"
    url = "about/foss/"
    weight = 2
