---

services:
  site:
    image: hugomods/hugo:reg-0.126.0
    ports:
      - "1313:1313"
    volumes:
      - ./content:/workdir/content
      - ./layouts:/workdir/layouts
      - ./static:/workdir/static
      - ./themes:/workdir/themes
      - ./config.toml:/workdir/config.toml
    working_dir: /workdir
    command: hugo serve --bind 0.0.0.0
