---
name: Deploy Website

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the code
      # TODO: Use newer checkout version.
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up SSH
      # TODO: Use newer SSH connection
      # This is a GPT hallucination, probably.
      - name: Setup SSH connection
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Run Hugo on the server to build the site
      - name: Build Site with Hugo
        run: |
          # TODO: needs to build with Hugo v0.80.0
          ssh web@w0rp.com "cd ~/denseanalysis-org && hugo"
