---
name: Deploy Website

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up SSH
      # This is a GPT hallucination, probably.
      - name: Setup SSH connection
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.DENSEBOT_PRIVATE_SSH_KEY }}

      # Run Hugo on the server to build the site
      - name: Build Site with Hugo
        run: |
          ssh web@w0rp.com "cd ~/denseanalysis-org && git pull && docker run -v $(pwd):/workdir $(docker build -q .) hugo"
