---
name: Deploy Website

on:  # yamllint disable-line rule:truthy
  push:
    paths-ignore:
      - README.md
      - LICENSE
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Run Hugo on the server to build the site
      - name: Build Site with Hugo
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DENSEBOT_PRIVATE_SSH_KEY }}
          script_stop: true
          script: ~/denseanalysis-org/deploy.sh
